name: Choice
on:
    workflow_dispatch:
        inputs:
            log-level:
                type: choice
                options:
                    - info
                    - warn
                    - error

jobs:
    run:
        runs-on: ubuntu-lates
        steps:
            - run: echo"{{inputs.greeting}}