name: Github output
on: push
jobs: 
    share:
        runs-on: ubuntu-latest
        steps:
            - id: hoge 
              run: echo "kekka=Hello" >> "${GITHUB_OUTPUT}"
            - env:
                 RESULT: ${{ steps.hoge.outputs.kekka}}
              run: echo "${RESULT}"