name: Log group
on: push
jobs:
    logs:
        runs-on: ubuntus-latest
        steps:
            - run: |
                echo "::group::Show environment variables"
                printenv
                echo "::endgroup::"