name: Naming
on: push
jobs:
    print:
        name: Super Useful Job
        runs-on: ubuntu-latest
        steps:
            - name: Amazing Script
              run: echo "Hello"
    print2:
        name: HOGE HOGE JOB
        runs-on: ubuntu-latest
        steps:
            - name: FUGA FUGA script
              run: echo "Hola!"