name: kokoni workflow name が入るよ！
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            WORKFLOW: ${{ github.workflow }}
        steps:
            - run: echo "${WORKFLOW}"