name: Status check functions
on: push
jobs:
    fail:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - run: echo "Hello"
              if: ${{ failure() }}
            - run: echo hoge
              if: ${{ success() }}
            - run: echo "fuga"
              if: ${{ failure() }}
            - run: echo "hoo"
              if: ${{ success() }}